config/routes.rb
Rails.application.routes.draw do

  root to: "home#index"

  devise_scope :user do
    post 'users/sign_up', to: 'devise/registrations#create'
    get '/users/sign_out' => 'devise/sessions#destroy'     
  end

  devise_for :users




  #routes for dashboard
  resources :dashboard


  # routes for accounts
  resources :accounts

  # routes for wallets
  resources :wallets

  # routes for transactions
  resources :transactions

end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController

	def index
		@income_trans = current_user.transactions.income
    @expense_trans = current_user.transactions.expense
    @bt_trans = current_user.transactions.bank_transfer
	end

	def edit
    @transaction = Transaction.find(params[:id])
  end

  def new
    @transaction = Transaction.new
  end



  def create

    if params[:transaction][:trans_type] == "income"

     # making unneccesary parameters for this transaction to be nill
     params[:transaction][:account_to] = nil
     params[:transaction][:expense_category] = nil
     params[:transaction][:trans_to_id] = nil
     params[:transaction][:trans_to_type] = nil
     
     add_income # adding the income to the account and make necessary transaction



    elsif params[:transaction][:trans_type] == "expense"
     params[:transaction][:account_to] = nil
     params[:transaction][:income_category] = nil
     add_expense # add expense to the account/wallet and make the transaction

    else
     params[:transaction][:expense_category] = nil
     params[:transaction][:income_category] = nil
     make_bank_transfer # do a bank transfer
    end
  
  end




  def update
    @trans = Transaction.find(params[:id])

    if @trans.update(trans_params)
      flash[:info] = "Transaction has been updated!"
			redirect_to transactions_path
    else
    	flash[:info] = "Unable to update your transaction, please check values!"
      render :edit
    end
  end

  def destroy
		@transaction = Transaction.find(params[:id])
		# restore expenses or income code here restore_money()
    trans_amount = @transaction.amount.to_f 
 
    if @transaction.trans_from_type == "Account"
      # restore amount back in the account
      acc = @transaction.trans_from
      current_amount = acc.current_amount.to_f
      new_amount = trans_amount + current_amount
      acc.update(current_amount: new_amount)
    else 
      # restore amount back in the wallet
      current_amount = current_user.wallet.current_amount.to_f
      new_amount = trans_amount + current_amount
      current_user.wallet.update(current_amount: new_amount)
    end

    authorize @transaction
    if @transaction.destroy
      flash[:info] = "Transaction deleted and transaction amount restored!"
  		redirect_to transactions_path
    else
      flash[:alert] = "Unable to undo the transaction"
      redirect_to transactions_path
    end
	end




  private
  def add_income
     if params[:transaction][:account_from] == "Wallet"
            # add money in wallet
            user_amount =  params[:transaction][:amount].to_f
            current_amount = current_user.wallet.current_amount.to_f
            new_amount = user_amount + current_amount
            
            # create transaction from wallet
            if current_user.wallet.update(current_amount: new_amount)
              trans = current_user.wallet.transactions.create(
                      trans_type: params[:transaction][:trans_type], 
                      amount: params[:transaction][:amount], 
                      date: params[:transaction][:date], 
                      description: params[:transaction][:description], 
                      income_category: params[:transaction][:income_category], 
                      user_id: current_user.id)

              flash[:info] = "Transaction sucessful and income added to your wallet account!"
              redirect_to dashboard_index_path
            else 
              flash[:alert] = "Income failed to be added to your account!"
              redirect_to dashboard_index_path
            end
      else 
      # adding income in account
            account_name = params[:transaction][:account_from]
            acc = current_user.accounts.find_by(name: account_name)            

            user_amount =  params[:transaction][:amount].to_f
            current_amount = acc.current_amount.to_f

            new_amount = user_amount + current_amount
            
            if acc.update(current_amount: new_amount)
              # create transaction from account
              trans = acc.transactions.create(
                      trans_type: params[:transaction][:trans_type], 
                      amount: params[:transaction][:amount], 
                      date: params[:transaction][:date], 
                      description: params[:transaction][:description], 
                      income_category: params[:transaction][:income_category], 
                      user_id: current_user.id)
              flash[:info] = "Transaction successful and income added to your account!"
              redirect_to dashboard_index_path
            else 
              flash[:alert] = "Income failed to be added to your account!"
              redirect_to dashboard_index_path
            end
      end
  end


  def add_expense
     if params[:transaction][:account_from] == "Wallet"
            # expense from wallet
            user_amount =  params[:transaction][:amount].to_f
            current_amount = current_user.wallet.current_amount.to_f

            if current_amount >= user_amount
              new_amount = current_amount - user_amount
              current_user.wallet.update(current_amount: new_amount)
              trans = current_user.wallet.transactions.create(
                      trans_type: params[:transaction][:trans_type], 
                      amount: params[:transaction][:amount], 
                      date: params[:transaction][:date], 
                      description: params[:transaction][:description], 
                      expense_category: params[:transaction][:expense_category], 
                      user_id: current_user.id)
              flash[:info] = "Transaction sucessful and amount deducted from your wallet!"
              redirect_to dashboard_index_path
            else
              flash[:alert] = "You do not have enough balance to make this transcation"
              redirect_to dashboard_index_path
            end
      else 
      # expense from account
            account_name = params[:transaction][:account_from]
            acc = current_user.accounts.find_by(name: account_name)

            user_amount =  params[:transaction][:amount].to_f
            current_amount = acc.current_amount.to_f
            if current_amount >= user_amount
              new_amount = current_amount - user_amount
              acc.update(current_amount: new_amount)
              trans = acc.transactions.create(
                      trans_type: params[:transaction][:trans_type], 
                      amount: params[:transaction][:amount], 
                      date: params[:transaction][:date], 
                      description: params[:transaction][:description], 
                      expense_category: params[:transaction][:expense_category], 
                      user_id: current_user.id)
              flash[:info] = "Transaction sucessful and amount deducted from your account!"
              redirect_to dashboard_index_path
            else
              flash[:alert] = "You do not have enough balance to make this transcation"
              redirect_to dashboard_index_path
            end
      end
  end

  def make_bank_transfer

    if params[:transaction][:account_from] == params[:transaction][:account_to]
      flash[:alert] = "You can not transfer money within an account!"
      return redirect_to dashboard_index_path
    end


    if params[:transaction][:account_from] == Wallet.name
      # tranfer from wallet
      user_amount =  params[:transaction][:amount].to_f
      current_wallet_amount = current_user.wallet.current_amount.to_f
      
      account_name = params[:transaction][:account_to]
      acc = current_user.accounts.find_by(name: account_name)
      current_acc_amount = acc.current_amount

      if current_wallet_amount >= user_amount
        # taking money out from wallet
        new_wallet_amount = current_wallet_amount - user_amount
        # adding money in the account
        new_account_amount = current_acc_amount + user_amount
        # updating wallet and ammount
        current_user.wallet.update(current_amount: new_wallet_amount) 
        acc.update(current_amount: new_account_amount)

        # saving the transaction
        trans = current_user.wallet.transactions.create(
                    trans_type: params[:transaction][:trans_type], 
                    amount: params[:transaction][:amount], 
                    date: params[:transaction][:date], 
                    description: params[:transaction][:description], 
                    trans_to_id: acc.id,
                    trans_to_type: "Account",
                    user_id: current_user.id)
        flash[:info] = "Bank transfer sucessful!"
        redirect_to dashboard_index_path
      else
        flash[:alert] = "You do not have sufficient balance in your wallet"
        redirect_to dashboard_index_path
      end


    else
      # transfer from account

      # case 1: transfer from account to wallet
      if params[:transaction][:account_to] == "Wallet"
          user_amount =  params[:transaction][:amount].to_f
          account_name = params[:transaction][:account_from]

          acc_from = current_user.accounts.find_by(name: account_name)
          current_acc_amount = acc_from.current_amount
          current_wallet_amount = current_user.wallet.current_amount.to_f

          if current_acc_amount >= user_amount

            # taking money out from the accunt
            new_account_amount = current_acc_amount - user_amount

            # adding money in wallet
            new_wallet_amount = current_wallet_amount + user_amount


            # updating wallet and account
            current_user.wallet.update(current_amount: new_wallet_amount) 
            acc_from.update(current_amount: new_account_amount)

            # saving the transaction
            trans = acc_from.transactions.create(

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/transactions/_form.html.erb
<div class="modal-body">
    <%= form_with model: transaction do |form| %>
    <div>
        <%= form.label :Transaction_Description %><br>
        <%= form.text_field :description, class: "form-control" %><br>
        <% transaction.errors.full_messages_for(:description).each do |message| %>
        <div>
            <%= message %>
        </div>
        <% end %>
    </div>
    <div>
        <%= form.label :Transaction_Category %><br>
        <%= form.text_field :category, class: "form-control"  %><br>
        <% transaction.errors.full_messages_for(:category).each do |message| %>
        <div>
            <%= message %>
        </div>
        <% end %>
    </div>
    <div>
        <%= form.label :Transaction_Type %><br>
        <%= form.select :trans_type, [["Income", "income"], ["Expense", "expense"]], {}, class: "form-select"%><br>
    </div>
    <div>
        <%= form.label :Amount %><br>
        <%= form.number_field :amount, class: "form-control" %><br>
        <% transaction.errors.full_messages_for(:amount).each do |message| %>
        <div>
            <%= message %>
        </div>
        <% end %>
    </div>
    <div>
        <%= form.label :Date %><br>
        <%= form.datetime_field :date, class: "form-control" %><br>
        <% transaction.errors.full_messages_for(:date).each do |message| %>
        <div>
            <%= message %>
        </div>
        <% end %>
    </div>
    <div>
        <%= form.submit "Update Transaction", class: "btn btn-primary" %>
    </div>
    <% end %>
</div>

app/views/transactions/edit.html.erb
<%= render partial: 'layouts/shared/navbar'%>
<hr>
<h4 class="text-primary">
    <%= link_to '<i class="bi bi-arrow-left-short text-info"></i>'.html_safe, transactions_path(),
                  method: :get%>
    Edit Transaction Details</h4>
<%= render "form", transaction: @transaction %>

app/views/transactions/index.html.erb
<%= render partial: 'layouts/shared/navbar'%>
<% if flash[:info] %>
<div class="alert-info border p-3">
    <%= flash[:info] %>
</div>
<% end %>
<% if flash[:alert] %>
<div class="alert-danger border p-3">
    <%= flash[:alert] %>
</div>
<% end %>
<!------------->
<hr>
<h4 class="text-primary col-7">Transactions History</h4>
<!----income table--->
<h5 class="text-center"><strong>Income Category</strong></h5>
<table class="table table-bordered">
    <thead class="text-info">
        <tr>
            <th scope="col">ID</th>
            <th scope="col">Type</th>
            <th scope="col">Description</th>
            <th scope="col">Category</th>
            <th scope="col">Account</th>
            <th scope="col">Amount</th>
            <th scope="col">Date</th>
            <th scope="col">Action</th>
        </tr>
    </thead>
    <tbody>
        <% @income_trans.each do |it| %>
        <tr>
            <td>
                <%= it.id %>
            </td>
            <td>
                <%= it.trans_type %>
            </td>
            <td>
                <%= it.description %>
            </td>
            <td>
                <%= it.income_category %>
            </td>
            <td>
                <% if it.trans_from_type == "Account" %>
                <%= current_user.accounts.find(it.trans_from_id).name %>
                <% else %>
                Wallet
                <% end %>
            </td>
            <td>
                <%= it.amount %>
            </td>
            <td>
                <%= it.date %>
            </td>
            <td>
                <%= link_to '<i class="bi bi-archive"></i>'.html_safe, transaction_path(it.id),
                  method: :delete,
                  data: { confirm: "Are you sure?" }, class: "btn btn-danger btn-block" %>
            </td>
        </tr>
        <% end %>
    </tbody>
</table>
<!--- expense table -->
<br>
<hr>
<br>
<h5 class="text-center"><strong>Expense Category</strong></h5>
<table class="table table-bordered">
    <thead class="text-info">
        <tr>
            <th scope="col">ID</th>
            <th scope="col">Type</th>
            <th scope="col">Description</th>
            <th scope="col">Category</th>
            <th scope="col">Account</th>
            <th scope="col">Amount</th>
            <th scope="col">Date</th>
            <th scope="col">Action</th>
        </tr>
    </thead>
    <tbody>
        <% @expense_trans.each do |et| %>
        <tr>
            <td>
                <%= et.id %>
            </td>
            <td>
                <%= et.trans_type %>
            </td>
            <td>
                <%= et.description %>
            </td>
            <td>
                <%= et.expense_category %>
            </td>
            <td>
                <% if et.trans_from_type == "Account" %>
                <%= current_user.accounts.find(et.trans_from_id).name %>
                <% else %>
                Wallet
                <% end %>
            </td>
            <td>
                <%= et.amount %>
            </td>
            <td>
                <%= et.date %>
            </td>
            <td>
                <%= link_to '<i class="bi bi-archive"></i>'.html_safe, transaction_path(et.id),
                  method: :delete,
                  data: { confirm: "Are you sure?" }, class: "btn btn-danger btn-block" %>
            </td>
        </tr>
        <% end %>
    </tbody>
</table>
<!--- Bank Transfer -->
<br>
<hr>
<br>
<h5 class="text-center"><strong>Bank Transfer Category</strong></h5>
<table class="table table-bordered">
    <thead class="text-info">
        <tr>
            <th scope="col">ID</th>
            <th scope="col">Type</th>
            <th scope="col">Description</th>
            <th scope="col">Account From</th>
            <th scope="col">Account To</th>
            <th scope="col">Amount</th>
            <th scope="col">Date</th>
        </tr>
    </thead>
    <tbody>
        <% @bt_trans.each do |bt| %>
        <tr>
            <td>
                <%= bt.id %>
            </td>
            <td>
                <%= bt.trans_type %>
            </td>
            <td>
                <%= bt.description %>
            </td>
            <td>
                <% if bt.trans_from_type == "Account" %>
                <%= current_user.accounts.find(bt.trans_from_id).name %>
                <% else %>
                Wallet
                <% end %>
            </td>
            <td>
                <% if bt.trans_to_type == "Account" %>
                <%= current_user.accounts.find(bt.trans_to_id).name %>
                <% else %>
                Wallet
                <% end %>
            </td>
            <td>
                <%= bt.amount %>
            </td>
            <td>
                <%= bt.date %>
            </td>
        </tr>
        <% end %>
    </tbody>
</table>

app/views/transactions/new.html.erb
<%= render partial: 'layouts/shared/navbar'%>
<hr>
<h4 class="text-primary">
    <%= link_to '<i class="bi bi-arrow-left-short text-info"></i>'.html_safe, dashboard_index_path,
                  method: :get%>
    Create Expense
</h4>
<%= form_with model: @transaction do |form| %>
<div>
    <%= form.label :Transaction_Description %><br>
    <%= form.text_field :description, class: "form-control" %><br>
    <% @transaction.errors.full_messages_for(:description).each do |message| %>
    <div>
        <%= message %>
    </div>
    <% end %>
</div>
<% if false %>
<div>
    <%= form.label :Transaction_Category %><br>
    <%= form.select :category, [
                    ["Food", "food"], 
                    ["Transport", "transport"],
                    ["Entertainment", "Entertainment"],
                    ["Rent", "Entertainment"],
                    ["Shopping", "Entertainment"],

        ], {}, class: "form-select"%><br>
    <% @transaction.errors.full_messages_for(:category).each do |message| %>
    <div>
        <%= message %>
    </div>
    <% end %>
</div>
<% end%>
<div>
    <%= form.label :Amount %><br>
    <%= form.number_field :amount, class: "form-control" %><br>
    <% @transaction.errors.full_messages_for(:amount).each do |message| %>
    <div>
        <%= message %>
    </div>
    <% end %>
</div>
<div>
    <%= form.label :Date %><br>
    <%= form.datetime_field :date, class: "form-control" %><br>
    <% @transaction.errors.full_messages_for(:date).each do |message| %>
    <div>
        <%= message %>
    </div>
    <% end %>
</div>
<div>
    <%= form.submit "Add Expense", class: "btn btn-primary" %>
</div>
<% end %>