config/routes.rb
Rails.application.routes.draw do

  root to: "home#index"

  devise_scope :user do
    post 'users/sign_up', to: 'devise/registrations#create'
    get '/users/sign_out' => 'devise/sessions#destroy'     
  end

  devise_for :users




  #routes for dashboard
  resources :dashboard


  # routes for accounts
  resources :accounts

  # routes for wallets
  resources :wallets

  # routes for transactions
  resources :transactions

end

app/models/account.rb
class Account < ApplicationRecord
	belongs_to :user
	has_many :transactions, as: :trans_from

	validates :name, uniqueness: { scope: :user_id,
    message: "This account already exists. Please create a unqiue account name." }

end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  def index
  	@user_accounts = current_user.accounts
  	@account = Account.new
	end

	def create
		puts current_user.email
		@account = current_user.accounts.new(account_params)
		if @account.save
			flash[:info] = "Account has been created succesfully!"
			redirect_to accounts_path
		else
			#flash[:alert] = @account.errors.first.full_message
			flash[:alert] = @account.errors[:name]
			redirect_to accounts_path
		end
	end

	def show
	end

	def edit
    @acc = Account.find(params[:id])
		authorize @acc
  end

   def update
    @acc = Account.find(params[:id])
    authorize @acc
    if @acc.update(account_params)
      flash[:info] = "Account details has been updated!"
			redirect_to accounts_path
    else
      render :edit
    end
  end

	def destroy
		@acc = Account.find(params[:id])

		authorize @acc
		@trans = @acc.transactions.destroy_all
    @acc.destroy
    flash[:info] = "Account deleted!"
		redirect_to accounts_path
	end

	private
	def account_params
		params.require(:account).permit(:name, :current_amount)
	end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/views/accounts/_form.html.erb
<div class="modal-body">
    <%= form_with model: account do |form| %>
    <div>
        <%= form.label :Account_Name %><br>
        <%= form.text_field :name, class: "form-control"  %>
        <% account.errors.full_messages_for(:name).each do |message| %>
        <div>
            <%= message %>
        </div>
        <% end %>
        <br>
    </div>
    <div>
        <%= form.label :Current_Balance %><br>
        <%= form.number_field :current_amount, class: "form-control" %><br>
        <% account.errors.full_messages_for(:current_amount).each do |message| %>
        <div>
            <%= message %>
        </div>
        <% end %>
    </div>
    <div>
        <%= form.submit "Update Account", class: "btn btn-primary" %>
    </div>
    <% end %>
</div>

app/views/accounts/edit.html.erb
<%= render partial: 'layouts/shared/navbar'%>
<hr>
<h4 class="text-primary">
    <%= link_to '<i class="bi bi-arrow-left-short text-info"></i>'.html_safe, accounts_path(),
                  method: :get%>
    Edit Account</h4>
<%= render "form", account: @acc %>

app/views/accounts/index.html.erb
<%= render partial: 'layouts/shared/navbar'%>
<% if flash[:info] %>
<div class="alert-info border p-3">
    <%= flash[:info] %>
</div>
<% end %>
<% if flash[:alert] %>
<div class="alert-danger border p-3">
    <%= flash[:alert][0] %>
</div>
<% end %>
<!------------->
<hr>
<div class="row">
    <h4 class="text-primary col-7">My Accounts</h4>
    <%= link_to '<i class="bi bi-wallet2"></i> My Wallet'.html_safe, wallet_path(current_user.wallet.id),
                  method: :get,class: "btn btn-info col-2 text-white"%>
    <!------------------------>
    &nbsp;&nbsp;&nbsp;
    <button type="" class="btn btn-success col-2" data-bs-toggle="modal" data-bs-target="#exampleModal">
        <i class="bi bi-pencil-square"></i>&nbsp;Add new account
    </button>
</div>
<table class="table">
    <thead class="text-info">
        <tr>
            <th scope="col">Account ID</th>
            <th scope="col">Account Name</th>
            <th scope="col">Current Amount</th>
            <th scope="col">Actions</th>
        </tr>
    </thead>
    <tbody>
        <% if @user_accounts.any? %>
        <% @user_accounts.each do |user_account| %>
        <tr>
            <td>
                <%= user_account.id %>
            </td>
            <td>
                <%= user_account.name %>
            </td>
            <td>
                <%= "#{user_account.current_amount} PKR" %>
            </td>
            <td>
                <div class="btn-group">
                    <!----Edit button--->
                    <%= link_to '<i class="bi bi-pencil-square"></i>'.html_safe, edit_account_path(user_account.id),
                  method: :get,class: "btn btn-primary btn-block" %>
                    <!------->
                    <!--destroy button-->
                    <%= link_to '<i class="bi bi-archive"></i>'.html_safe, account_path(user_account.id),
                  method: :delete,
                  data: { confirm: "Are you sure?" }, class: "btn btn-danger btn-block" %>
                    <!--delete button-->
                </div>
            </td>
        </tr>
        <% end %>
        <% else %>
        <tr>
            <td colspan="4" rowspan="4" headers="">No data to display.</td>
        </tr>
        <% end %>
    </tbody>
</table>
<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true" data-controller="accounts">
    <div class="modal-dialog">
        <%= simple_form_for @account do |f| %>
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Add new account details</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <%= f.input :name, label: 'Account Name' ,error: 'Account name is mandatory!' %>
                <%= f.input :current_amount, 'data-target' => "accounts.current_amount",label: 'Opening Balance',error: 'Enter a valid amount to continue!' %>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <%= f.button :submit, label: 'Create account', class: 'btn btn-primary' %>
            </div>
        </div>
    </div>
    <% end %>
    <!--
    <button type="" data-action="click->accounts#changeAmount">Click for magic!</button>
    --->
</div>